package com.kw.readwith.domain.enums;

public enum NormalizationFailureCode {
    INVALID_EPUB_ARCHIVE,
    SOURCE_STORE_FAILED,
    SOURCE_DOWNLOAD_FAILED,
    TEMP_FILE_PREPARE_FAILED,
    CONTAINER_NOT_FOUND,
    CONTAINER_PARSE_FAILED,
    PACKAGE_NOT_FOUND,
    PACKAGE_PARSE_FAILED,
    SPINE_RESOLVE_FAILED,
    SPINE_ENTRY_NOT_FOUND,
    XHTML_PARSE_FAILED,
    NO_TEXT_CHAPTERS,
    VALIDATION_FAILED,
    ARTIFACT_UPLOAD_FAILED,
    PROJECTION_WRITE_FAILED,
    UNEXPECTED_FAILURE
}
